ALTER TABLE ordert
DROP CONSTRAINT 
	order_fk,
ADD CONSTRAINT 
	order_fk FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE;

ALTER TABLE order_line
DROP CONSTRAINT
	ORDER_LINE_FK1,
ADD CONSTRAINT
	ORDER_LINE_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERT(ORDER_ID) ON DELETE CASCADE;
	
DELETE FROM customer WHERE customer_id = 10001;

select * from customer;
select * from ordert;
select * from order_line;